# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Parameter.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.setEnabled(False)
        Widget.resize(210, 325)
        Widget.setMinimumSize(QtCore.QSize(210, 325))
        Widget.setMaximumSize(QtCore.QSize(210, 325))
        self.Parameter = QtWidgets.QTableWidget(Widget)
        self.Parameter.setEnabled(False)
        self.Parameter.setGeometry(QtCore.QRect(0, 0, 275, 435))
        self.Parameter.setMinimumSize(QtCore.QSize(275, 435))
        self.Parameter.setMaximumSize(QtCore.QSize(275, 435))
        self.Parameter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Parameter.setShowGrid(True)
        self.Parameter.setGridStyle(QtCore.Qt.SolidLine)
        self.Parameter.setWordWrap(False)
        self.Parameter.setCornerButtonEnabled(False)
        self.Parameter.setRowCount(8)
        self.Parameter.setColumnCount(1)
        self.Parameter.setObjectName("Parameter")
        item = QtWidgets.QTableWidgetItem()
        self.Parameter.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Parameter.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Parameter.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Parameter.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Parameter.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Parameter.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Parameter.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.Parameter.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.Parameter.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Parameter.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Parameter.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Parameter.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Parameter.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Parameter.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.Parameter.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.Parameter.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.Parameter.setItem(7, 0, item)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Confirm parameters"))
        self.Parameter.setSortingEnabled(False)
        item = self.Parameter.verticalHeaderItem(0)
        item.setText(_translate("Widget", "Size"))
        item = self.Parameter.verticalHeaderItem(1)
        item.setText(_translate("Widget", "r"))
        item = self.Parameter.verticalHeaderItem(2)
        item.setText(_translate("Widget", "h"))
        item = self.Parameter.verticalHeaderItem(3)
        item.setText(_translate("Widget", "Threshold"))
        item = self.Parameter.verticalHeaderItem(4)
        item.setText(_translate("Widget", "R Square"))
        item = self.Parameter.verticalHeaderItem(5)
        item.setText(_translate("Widget", "Alpha1"))
        item = self.Parameter.verticalHeaderItem(6)
        item.setText(_translate("Widget", "Alpha2"))
        item = self.Parameter.verticalHeaderItem(7)
        item.setText(_translate("Widget", "J"))
        item = self.Parameter.horizontalHeaderItem(0)
        item.setText(_translate("Widget", "Value"))
        __sortingEnabled = self.Parameter.isSortingEnabled()
        self.Parameter.setSortingEnabled(False)
        self.Parameter.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
